export const doctypeData =   [{dtgrid:"102",dtgrname:"Accounts Payable",id:"170",name:"AP ACH Election Form"},
{dtgrid:"102",dtgrname:"Accounts Payable",id:"121",name:"AP Correspondence"},
{dtgrid:"102",dtgrname:"Accounts Payable",id:"114",name:"AP Create New Vendor Request (EForm)"},
{dtgrid:"102",dtgrname:"Accounts Payable",id:"120",name:"AP Credit Memo"},
{dtgrid:"102",dtgrname:"Accounts Payable",id:"169",name:"AP Freight"},
{dtgrid:"102",dtgrname:"Accounts Payable",id:"149",name:"AP Freight (Image)"},
{dtgrid:"102",dtgrname:"Accounts Payable",id:"168",name:"AP Freight (Redacted)"},
{dtgrid:"102",dtgrname:"Accounts Payable",id:"165",name:"AP Freight (Review Image)"},
{dtgrid:"102",dtgrname:"Accounts Payable",id:"166",name:"AP Freight Reindex (Virtual EForm)"},
{dtgrid:"102",dtgrname:"Accounts Payable",id:"167",name:"AP Freight Review (Virtual EForm)"},
{dtgrid:"102",dtgrname:"Accounts Payable",id:"151",name:"AP Invoice Approved Outside OnBase"},
{dtgrid:"102",dtgrname:"Accounts Payable",id:"124",name:"AP Invoice NonPO (Image)"},
{dtgrid:"102",dtgrname:"Accounts Payable",id:"126",name:"AP Invoice NonPO (Redacted Image)"},
{dtgrid:"102",dtgrname:"Accounts Payable",id:"147",name:"AP Invoice NonPO (Review Image)"},
{dtgrid:"102",dtgrname:"Accounts Payable",id:"141",name:"AP Invoice NonPO Reindex (Virtual EForm)"},
{dtgrid:"102",dtgrname:"Accounts Payable",id:"140",name:"AP Invoice NonPO Review (Virtual EForm)"},
{dtgrid:"102",dtgrname:"Accounts Payable",id:"113",name:"AP Invoice PO (Image)"},
{dtgrid:"102",dtgrname:"Accounts Payable",id:"125",name:"AP Invoice PO (Redacted Image)"},
{dtgrid:"102",dtgrname:"Accounts Payable",id:"148",name:"AP Invoice PO (Review Image)"},
{dtgrid:"102",dtgrname:"Accounts Payable",id:"171",name:"AP Invoice Pre Approved Freight (Image)"},
{dtgrid:"102",dtgrname:"Accounts Payable",id:"172",name:"AP Invoice Pre Approved Freight (Review Image)"},
{dtgrid:"102",dtgrname:"Accounts Payable",id:"150",name:"AP Invoice Pre OnBase"},
{dtgrid:"102",dtgrname:"Accounts Payable",id:"161",name:"AP Invoice Recurring (Image)"},
{dtgrid:"102",dtgrname:"Accounts Payable",id:"162",name:"AP Invoice Recurring (Redacted Image)"},
{dtgrid:"102",dtgrname:"Accounts Payable",id:"163",name:"AP Invoice Recurring (Review Image)"},
{dtgrid:"102",dtgrname:"Accounts Payable",id:"146",name:"AP M2K Payment Detail (Virtual EForm)"},
{dtgrid:"102",dtgrname:"Accounts Payable",id:"116",name:"AP MWDBE Certificate"},
{dtgrid:"102",dtgrname:"Accounts Payable",id:"117",name:"AP Non-Disclosure Agreement"},
{dtgrid:"102",dtgrname:"Accounts Payable",id:"124",name:"AP Payment"},
{dtgrid:"102",dtgrname:"Accounts Payable",id:"160",name:"AP Purchase Order"},
{dtgrid:"102",dtgrname:"Accounts Payable",id:"119",name:"AP Review New Vendor Request (EForm)"},
{dtgrid:"102",dtgrname:"Accounts Payable",id:"133",name:"AP Signature Card"},
{dtgrid:"102",dtgrname:"Accounts Payable",id:"122",name:"AP Statement"},
{dtgrid:"102",dtgrname:"Accounts Payable",id:"112",name:"AP Unidentified Document"},
{dtgrid:"102",dtgrname:"Accounts Payable",id:"134",name:"AP VD Request - Book Transfer (Virtual EForm)"},
{dtgrid:"102",dtgrname:"Accounts Payable",id:"131",name:"AP VD Request - Check (Virtual EForm)"},
{dtgrid:"102",dtgrname:"Accounts Payable",id:"136",name:"AP VD Request - Debit Advice (Virtual EForm)"},
{dtgrid:"102",dtgrname:"Accounts Payable",id:"135",name:"AP VD Request - Wire (Virtual EForm)"},
{dtgrid:"102",dtgrname:"Accounts Payable",id:"137",name:"AP VD Review - Book Transfer (Virtual EForm)"},
{dtgrid:"102",dtgrname:"Accounts Payable",id:"132",name:"AP VD Review - Check (Virtual EForm)"},
{dtgrid:"102",dtgrname:"Accounts Payable",id:"138",name:"AP VD Review - Debit Advice (Virtual EForm)"},
{dtgrid:"102",dtgrname:"Accounts Payable",id:"139",name:"AP VD Review - Wire (Virtual EForm)"},
{dtgrid:"102",dtgrname:"Accounts Payable",id:"115",name:"AP W9 Form"},
{dtgrid:"102",dtgrname:"Accounts Payable",id:"164",name:"zAP Freight Games"},
{dtgrid:"103",dtgrname:"Accounts Receivable",id:"154",name:"AR Credit Memo"},
{dtgrid:"103",dtgrname:"Accounts Receivable",id:"155",name:"AR GDR"},
{dtgrid:"103",dtgrname:"Accounts Receivable",id:"153",name:"AR Invoice (Packet)"},
{dtgrid:"103",dtgrname:"Accounts Receivable",id:"156",name:"AR Other Documents"},
{dtgrid:"104",dtgrname:"Signature Authority",id:"159",name:"SA Signature Authority FormR"}]                                       
                                                  
                                                                                                                                                                                                                                                               


